In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\ASUS\Desktop\data.csv", encoding='latin1')

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [6]:
df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')

In [7]:
df.columns

Index(['invoiceno', 'stockcode', 'description', 'quantity', 'invoicedate',
       'unitprice', 'customerid', 'country'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoiceno    541909 non-null  object
 1   stockcode    541909 non-null  object
 2   description  540455 non-null  object
 3   quantity     541909 non-null  int64
 4   invoicedate  541909 non-null  object
 5   unitprice    541909 non-null  float64
 6   customerid   406829 non-null  float64
 7   country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [9]:
df.isnull().sum()

invoiceno           0
stockcode           0
description      1454
quantity            0
invoicedate         0
unitprice           0
customerid     135080
country             0
dtype: int64

In [11]:
df = df.dropna(subset=['customerid'])

In [12]:
df['customerid'] = df['customerid'].astype(int)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_5440\1039371951.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customerid'] = df['customerid'].astype(int)

In [13]:
df.isnull().sum()

invoiceno      0
stockcode      0
description    0
quantity       0
invoicedate    0
unitprice      0
customerid     0
country        0
dtype: int64

In [14]:
df.shape

(406829, 8)

In [15]:
(df['quantity'] < 0).sum()

np.int64(8905)

In [16]:
(df['unitprice'] <= 0).sum()

np.int64(40)

In [17]:
df = df[(df['quantity'] > 0) & (df['unitprice'] > 0)]

In [18]:
(df['quantity'] < 0).sum()

np.int64(0)

In [19]:
(df['unitprice'] <= 0).sum()

np.int64(0)

In [20]:
df.shape

(397884, 8)

In [21]:
df['totalprice'] = df['quantity'] * df['unitprice']

In [22]:
df['invoicedate'] = pd.to_datetime(df['invoicedate'])

In [25]:
df[['quantity','unitprice','totalprice']].head()

   quantity  unitprice  totalprice
0         6       2.55       15.30
1         6       3.39       20.34
2         8       2.75       22.00
3         6       3.39       20.34
4         6       3.39       20.34

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397884 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoiceno    397884 non-null  object
 1   stockcode    397884 non-null  object
 2   description  397884 non-null  object
 3   quantity     397884 non-null  int64
 4   invoicedate  397884 non-null  datetime64[ns]
 5   unitprice    397884 non-null  float64
 6   customerid   397884 non-null  int64
 7   country      397884 non-null  object
 8   totalprice   397884 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 30.4+ MB

In [26]:
df.duplicated().sum()

np.int64(5192)

In [27]:
df = df.drop_duplicates()

In [28]:
df.shape

(392692, 9)

In [29]:
df.isnull().sum()

invoiceno      0
stockcode      0
description    0
quantity       0
invoicedate    0
unitprice      0
customerid     0
country        0
totalprice     0
dtype: int64

In [30]:
reference_date = df['invoicedate'].max()

In [31]:
rfm = df.groupby('customerid').agg({
    'invoicedate': 'max',
    'invoiceno': 'nunique',
    'totalprice': 'sum'
})

In [32]:
rfm.columns = ['last_purchase', 'frequency', 'monetary']

In [33]:
rfm['recency'] = (reference_date - rfm['last_purchase']).dt.days

In [34]:
rfm = rfm[['recency', 'frequency', 'monetary']]

In [35]:
rfm.head()

            recency  frequency  monetary
customerid
12346           325          1  77183.60
12347             1          7   4310.00
12348            74          4   1797.24
12349            18          1   1757.55
12350           309          1    334.40

In [36]:
def segment(row):
    if row['recency'] <= 30 and row['frequency'] >= 5:
        return 'High Value'
    elif row['recency'] > 90:
        return 'At Risk'
    else:
        return 'Regular'

rfm['segment'] = rfm.apply(segment, axis=1)

In [37]:
rfm.head()

            recency  frequency  monetary     segment
customerid
12346           325          1  77183.60     At Risk
12347             1          7   4310.00  High Value
12348            74          4   1797.24     Regular
12349            18          1   1757.55     Regular
12350           309          1    334.40     At Risk

In [38]:
rfm['segment'].value_counts()

segment
Regular       2082
At Risk       1445
High Value     811
Name: count, dtype: int64

In [39]:
df['customerid'].nunique()

4338

In [40]:
rfm.shape

(4338, 4)

In [41]:
df['stockcode'] = df['stockcode'].astype(str)

In [42]:
df.to_csv("cleaned_retail_data.csv", index=False)

In [43]:
rfm.to_csv("rfm_table.csv")

In [44]:
import os
os.getcwd()

'C:\\Users\\ASUS\\Customer segmentation final'

In [45]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (2.0.47)
Requirement already satisfied: pymysql in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\ASUS\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [48]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:12345@localhost/retail_project")

In [49]:
df.to_sql('cleaned_retail_data', con=engine, if_exists='replace', index=False)

392692